# Site settings
title: 九弦之都
description: >
  一个静谧的花园

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.sinzmise.top" # the base hostname & protocol for your site

author:
  fullname: 王九弦SZ·Ninty
  github: SinzMise
  linkedin: 
  email: email@sinzmise.top


# Syntax highlighting
highlightstyle: 'xcode'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Comment settings
comments_provider: twikoo

# https://disqus.com
disqus:
    username: 

lazy_load_disqus: false

# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 
    repo: 
    clientID: 
    clientSecret: 
# https://utteranc.es/
utterances:
    repo: 
# https://beaudar.lipk.org/
beaudar:
    repo: 
# https://giscus.app/zh-CN
giscus:
    repo: 
    repo-id: 
    category: 
    category-id: 
# https://twikoo.js.org
twikoo:
    envId: https://twk.sinzmise.cf/
    region: 
    lang: zh-CN
# https://detalk.js.org
detalk:
    url:

# Build settings
highlighter: null
markdown: kramdown

# Pjax settings
pjax: true

inject:
  head:
  bottom:
    - <script async src="https://status.sinzmise.top/a8f9c04189c7d6a2b6b03f4f3948ef41" data-website-id="a87715ab-c2b6-488b-baa2-cbd28a2cb9e3"></script>
    - <script src="/assets/js/YingHua.min.eval.js"></script>

cdn:
  option:
    # fontawesome:
    # highlight_css:
    # normalize:
    # highlight: 
    # gitalk_css:
    # gitalk_js:  
    # detalk: 